静态代码检查工具

diff --git a/config/pre-commit b/config/pre-commit
--- a/config/pre-commit
+++ b/config/pre-commit
@@ -22,5 +22,18 @@ if [ $EXIT_CODE -ne 0 ]; then
   exit $EXIT_CODE
 fi
 
+cd ./plugins
+./gradlew detekt
+EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  echo "***********************************************"
+  echo "                 Detekt failed                 "
+  echo " Please fix the above issues before committing "
+  echo "***********************************************"
+  cd ..
+  exit $EXIT_CODE
+fi
+cd ..
+
 echo "执行 checkstyle 任务 "
 ./gradlew checkstyle
